apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ceph-csi-operator.resourceName" (dict "suffix" "nfs-nodeplugin-cr" "context" $) }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
