{{- $root := . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ceph-csi-operator.resourceName" (dict "suffix" "controller-manager" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ceph-csi-operator.labels" . | nindent 4 }}
{{- with .Values.manager.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ceph-csi-operator.resourceName" (dict "suffix" "cephfs-ctrlplugin-sa" "context" $) }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.manager.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ceph-csi-operator.resourceName" (dict "suffix" "cephfs-nodeplugin-sa" "context" $) }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.manager.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ceph-csi-operator.resourceName" (dict "suffix" "nfs-ctrlplugin-sa" "context" $) }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.manager.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ceph-csi-operator.resourceName" (dict "suffix" "nfs-nodeplugin-sa" "context" $) }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.manager.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ceph-csi-operator.resourceName" (dict "suffix" "nvmeof-ctrlplugin-sa" "context" $) }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.manager.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ceph-csi-operator.resourceName" (dict "suffix" "nvmeof-nodeplugin-sa" "context" $) }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.manager.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ceph-csi-operator.resourceName" (dict "suffix" "rbd-ctrlplugin-sa" "context" $) }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.manager.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ceph-csi-operator.resourceName" (dict "suffix" "rbd-nodeplugin-sa" "context" $) }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.manager.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . | indent 2 }}
{{- end }}
